default: &default
  idec_api_url: https://feirasorganicas.org.br/wp-json/wp/v2
  idec_uploads_url: https://feirasorganicas.org.br/wp-content/uploads/
  csv_file_path: https://feirasorganicas.org.br/?export=csv
  geosampa_file_url: http://wfs.geosampa.prefeitura.sp.gov.br/geoserver/geoportal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geoportal:equipamento_feira_livre&maxFeatures=2000&outputFormat=csv
  email_sender: <%= ENV['EMAIL_SENDER'] %>

development:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY'] %>

staging:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY'] %>

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY'] %>
