attributes:
  - family_work
  - name
  - email
  - source
  - associativism
  - references
  - park
  - zone
  - category_name
  - description
  - cultivated_area_range
  - area_range
  - subcategory_list
  - qualification_list
  - source_info
  - neighborhood_region_list
  - web_pages
  - where_find_list
  - farms_count
  - visible_product_list
  - certificate_list
  - gender
  - dap
  - connections_resume
  - phone_0
  - phone_kind_0
  - phone_1
  - phone_kind_1
  - resume_address
  - neighborhood
  - district
