attributes:
  - name
  - email
  - source
  - disabled_friendly_amenities
  - associativism
  - references
  - park
  - zone
  - category_name
  - description
  - subcategory_list
  - qualification_list
  - source_info
  - neighborhood_region_list
  - web_pages
  - where_find_list
  - visible_product_list
  - farms_count
  - schedule
  - gender
  - begined_at
  - connections_resume
  - phone_0
  - phone_kind_0
  - phone_1
  - phone_kind_1
  - resume_address
  - neighborhood
  - zip_code
  - district
  - lat
  - lon
