api_id: unidade_produtiva_id
user_id:  produtor_id
responsable_name: produtor_nome
cpf: produtor_cpf
registration_name: unidade_produtiva_nome
email: produtor_email
registration_phone_0: produtor_telefone_1
registration_phone_1: produtor_telefone_2
full_address: unidade_produtiva_endereco
neighborhood: unidade_produtiva_bairro
city: unidade_produtiva_cidade
state: unidade_produtiva_estado
zip_code: unidade_produtiva_cep
product_list: unidade_produtiva_producao
where_find_list: unidade_produtiva_onde_comprar
certificate_list: unidade_produtiva_certificacao
cultivated_area: unidade_produtiva_area_cultivada
area: unidade_produtiva_area_total
family_work: produtor_agricultura_familiar
associativism: produtor_associacao
dap: produtor_dap
birthdate: produtor_data_nascimento
gender: produtor_genero
has_internet_access: produtor_acessa_internet
_lat: unidade_produtiva_lat
_lon: unidade_produtiva_lng
