api_id: "ID"
is_public: "Publicar"
category_name: "Categoria"
subcategory_list: "Subcategoria"
name: "Nome no Perfil"
qualification_list: "Qualificações"
product_list: "Atividade de conexão"
where_find_list: "Onde Comprar*"
full_address: "Endereço"
neighborhood: "Bairro"
zip_code: "CEP"
district: "Distrito"
city: "Cidade "
zone: "Zona"
_lat: "Latitude"
_lon: "Longitude"
schedule: "Período Funcionamento"
commercial_phone_0: "Telefone 1"
commercial_phone_kind_0: "Tel 1 - tipo"
commercial_phone_1: "Telefone 2"
commercial_phone_kind_1: "Tel 2 - tipo"
email: "e-mail"
web_pages: "Site/Blog/Redes Sociais"
other_contact: "Outra forma de contato"
description: "Descrição"
# related_partner_list: "Conexões"
farms_count: "Número de roças*"
associativism: "Associação"
park: "Estacionamento"
disabled_friendly_amenities: "Acessibilidade"
neighborhood_region_list: "Polo de ecoturismo [cantareira, parelheiros, leste]* "
gender: "Gênero da responsável"
begined_at: "Ano de início da atividade"
responsable_name: "Nome de Contato - cadastro"
cpf: "CPF"
registration_email: "E-mail - cadastro"
registration_phone_0: "Telefone 1- cadastro"
registration_phone_1: "Telefone 2- cadastro"
registered_by: "Responsável pela coleta"
other_information: "Informações complementares - cadastro"
cnpj: "CNPJ - Cadastro"
cnae: "Código CNAE - cadastro*"
company_activity: "Atividade econômica - cadastro*"
source_info: "Fonte"
source_info2: "Fonte 2"
source_date: "Data"
source_update: "Data da última atualização"
contact: "Entre em contato"
