attributes:
  api_id: id
  tags_list: tag
  subcategory_list: subcategoria
  description: descritivo
  phone: telefone
  begined_at: incio_da_atividade
  site: site
  email: email
  work_season: perodo_de_funcionamento
  open_in_holidays: funcionamento_em_feriados
  rules: outras_regras_e_informaes
  associativism: associativismo
  park: estacionamento
  disabled_friendly_amenities: possui_alguma_facilidade_para_pessoas_com_deficincia_ou_mobilidade_reduzida
  neighborhood_region: polo
  references: referncias
  publish_address: publicar_endereo
  publish_phone: publicar_telefone
  registration_email: email_de_cadastro
  cnpj: cnpj
  cnae: cnae
  company_activity: atividade_econmica
  activities_list: atividades
  name: ttulo
  schedule: dias_e_horrios_de_funcionamento
  is_public: publicar
  district: distrito
  city: municipio
  state: estado
  _lat: latitude
  _lon: longitude
  full_address: endereo
  neighborhood: bairrolocalidade
  zip_code: cep
