api_id: "ID"
responsable_name: "Nome produtor/a - cadastro"
cpf: "CPF"
registration_name: "Nome da Unidade Produtiva - cadastro"
registration_email: "E-mail - cadastro"
registration_phone_0: "Telefone residencial- cadastro"
registration_phone_1: "Telefone celular - cadastro"
registration_address: "Endereço cadastro"
registration_neighborhood: "Bairro cadastro"
city: "Cidade"
registration_zip_code: "CEP cadastro"
registered_by: "Responsável pela coleta"
other_information: "Informações complementares - cadastro"
public_attachments: "Autorização da divulgação de imagens ATER"
category_name: "Categoria"
subcategory_list: "Subcategoria"
name: "Nome no Perfil"
qualification_list: "Qualificações"
product_list: "Produção"
fruit_specy_list: "Se produz frutas para comercialização, quais especies?"
where_find_list: "Onde Comprar"
who_sells_details: "Detalhes sobre os estabelecimentos que comercializam os produtos"
full_address: "Endereço"
neighborhood: "Bairro"
district: "Distrito"
zone: "Zona"
commercial_phone_0: "Telefone 1"
commercial_phone_1: "Telefone 2"
commercial_phone_kind_0: "Tel 1 - tipo"
commercial_phone_kind_1: "Tel 2 - tipo"
email: "e-mail"
web_pages: "Site/Blog/Redes Sociais"
contact: "Entre em contato"
other_contact: "Outra forma de contato"
description: "Descrição"
related_partner_list: "Conexões"
certificate_list: "Certificação Orgânica/Transição"
cultivated_area: "Area cultivada (Ha)"
area: "Area da UPA (Ha)"
family_work: "Agricultura Familiar"
associativism: "Associação"
dap: "DAP"
birthdate: "Idade"
gender: "Gênero da responsável"
has_internet_access: "Acessa a Internet?"
source: "Fonte"
_lat: "Latitude"
_lon: "Longitude"
source_info: "Fonte"
source_info2: "Fonte 2"
source_date: "Data da Coleta "
source_update: "Data da última atualização"
